version: "{build}"

branches:
  except:
  - master

environment:
  - nodejs_version: "4"
  - nodejs_version: "5"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test

build: off
